### ISSUE TITLE
checklist creation from template

### ISSUE THREAD

**Issue by mvcorrea** [isel-leic-ls/1617-1-common#2]
Boas Prof,

na situação a seguir

```
POST /templates name=tmpl1&desc=my+tmpl   -> 01
POST /templates/1/tasks name=tsk1&desc=my+tsk1
POST /templates/1/tasks name=tsk2&desc=my+tsk2
```

no anterior foi criado uma template com 2 tasks

`POST /templates/1/create name=chkLst1&desc=my+chkLst1`

e foi criada uma checklist a partir da template.

a pergunta é, em que situação, na criação da checklist a partir de um template utilizarei a opção duedate? (já que o conteúdo de todas as tasks inclusas não tem duedate)

Uma checklist pode ter duedate com algum integrante(tasks) sem duedate?

cumpts,
Marcelo

**Comment by pmhsfelix** [comment]
- A criação de uma _checklist_ a partir de um _template_ pode incluir a definição da `dueDate` para a _checklist criada_ (e não para as tasks integrantes).
- Sim, uma _checklist_ pode ter `dueDate` sem nenhuma das _tasks_ o ter.
