### ISSUE TITLE
POST /checklists/{cid}/tags

### ISSUE THREAD

**Issue by AndreFonsecaa** [isel-leic-ls/1617-1-common#3]
Boas Eng,

POST /checklists/{cid}/tags - associate a tag to the cid checklist, given the following parameters
    -gid- the tag unique identifier.

neste comando é suposto recebermos também o Gid da tag? ficando assim o comando:
POST /checklists/{cid}/tags/{gid}

cumprimentos,
André Fonseca

**Comment by pmhsfelix** [comment]
O gid  é passado nos parâmetros e não no caminho
