### ISSUE TITLE
Interative operation

### ISSUE THREAD

**Issue by GuiRocha** [isel-leic-ls/1617-1-common#4]
Boa noite Sr. Eng.

Quando é dito no enunciado "If the application is called with empty arguments, then it should enter into an interactive mode." é suposto criar uma aplicação que leia sucessivamente da linha de comandos diversos comandos até ordem de fim de aplicação. Se a aplicação receber directamente argumentos em args é suposto terminar de seguida ou voltar a pedir argumentos, desta vez na linha de comandos?

Guilherme Rocha

**Comment by pmhsfelix** [comment]
1) Sem argumentos da linha de comando, entra em ciclo a ler comandos do
standard input até ao comando EXIT.
2) Com argumentos da linha de comando, executa esse comando e termina
imediatamente.
